[tool.poetry]
name = "chat-bot"
version = "0.1.0"
description = ""
authors = ["hermeschen1116 <108386417+hermeschen1116@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.0.0"
torch = "^2.2.1"
datasets = "^2.18.0"
accelerate = "^0.27.2"
tensorboard = "^2.16.2"
huggingface-hub = "^0.21.3"
peft = "0.4.0"
bitsandbytes = "0.40.2"
transformers = "4.31.0"
trl = "0.4.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
