[tool.poetry]
name = "chat-bot"
version = "0.1.0"
description = ""
authors = [
    "hermeschen1116 <108386417+hermeschen1116@users.noreply.github.com>",
    "yangyx30678 <yangyx0000001@gmail.com>"
]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.11"
wheel = "^0.43.0"
<<<<<<< Updated upstream
torch = "^2.2.2"
huggingface-hub = "^0.21.3"
datasets = "^2.18.0"
||||||| Stash base
torch = "^2.3.0"
datasets = "^2.18.0"
=======
torch = "^2.3.0"
datasets = "^2.19.0"
>>>>>>> Stashed changes
peft = "^0.9.0"
trl = "^0.7.11"
transformers = "4.38.2"
accelerate = "^0.28.0"
evaluate = "^0.4.1"
wandb = "^0.16.5"
torcheval = "^0.0.7"
<<<<<<< Updated upstream
python-dotenv = "^1.0.1"

[tool.poetry.group.cuda.dependencies]
flash-attn = "^2.5.6"
bitsandbytes = "^0.42.0"
||||||| Stash base
flash-attn = "^2.5.6"
lightning = "^2.2.3"
=======
flash-attn = "^2.5.8"
lightning = "^2.2.3"
>>>>>>> Stashed changes

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
