[tool.poetry]
name = "chat-bot"
version = "0.1.0"
description = "NCU special project"
authors = ["hermeschen1116 <108386417+hermeschen1116@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
peft = "^0.9.0"
datasets = "^2.17.1"
huggingface-hub = "^0.21.3"
torch = {url = "https://download.pytorch.org/whl/cpu/torch-2.2.1-cp312-none-macosx_11_0_arm64.whl"}
trl = "^0.7.11"
bitsandbytes = "^0.42.0"
jupyter = "^1.0.0"
accelerate = "^0.27.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
